spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_issuesserver
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
