spring:
	jpa.hibernate.ddl-auto: update
	datasource:
	    url: jdbc:mysql://localhost:3306/reaktor_issuesserver
	    username: root
	    password: toor
	    hikari:
	      connection-timeout: 60000
	      maximum-pool-size: 5

server:
	port: 8082